name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2021.04.05
  - jupyterlab=3
  - pip=20
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - pydata-sphinx-theme
  - livereload
  - xlrd
  - imagemagick
  - mysql
  - openjdk
  - zeromq
  - pyzmq
  - datashader
  - gcsfs
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - matplotlib-base
  - nb_conda_kernels
  - panel
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - sparse
  - wxpython
  - pip:
      - CellProfiler==4.0.7
      - jupyter-rsession-proxy
      - jupyter-book
      - jupyter-cache[cli]
      - git+https://github.com/bashtage/sphinx-material.git
