name: napari
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.12.22
  - jupyterlab=2.2.9
  - pip=20
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - h5netcdf
  - h5py
  - jupyterlab-nvdashboard
  - matplotlib-base
  - nb_conda_kernels
  - scikit-learn
  - scipy
  - napari=0.4.2
  - pip:
    - jupyter-rsession-proxy
    - jupyter-book
    - jupyter-cache[cli]
