name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  {%- for package in cookiecutter.default_packages.conda_packages %}
  - {{ package }}
  {%- endfor %}
  - imagemagick
  - mysql
  - openjdk
  - zeromq
  - pyzmq
  - datashader
  - gcsfs
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - matplotlib-base
  - nb_conda_kernels
  - panel
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - sparse
  #- gtk3
  - gtk2
  - wxpython=4.1.0
  - pip:
      - CellProfiler==4.1.3
  {%- for package in cookiecutter.default_packages.pip_packages %}
      - {{ package }}
  {%- endfor %}
