name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.8*
  - pangeo-notebook=2021.04.05
  - jupyterlab=3
  - pip=20
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - prefect
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - parallel
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - pydata-sphinx-theme
  - livereload
  - xlrd
  - r-base=4.0.3
  - r-essentials
  - r-tidyverse
  - r-bookdown
  - pip:
    - jupyter-rsession-proxy
    - jupyter-book
    - jupyter-cache[cli]
    - git+https://github.com/bashtage/sphinx-material.git
